version: '3.8'

services:
  n8n:
    build:
      context: .
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - TZ=Europe/Berlin
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - N8N_HOST=n8n.local
      - N8N_PORT=5678
      - WEBHOOK_URL=http://n8n.local:5678/
    volumes:
      - /usr/docker_data/n8n:/home/node/.n8n
      - ./scripts:/scripts
    networks:
      - ha_network

networks:
  ha_network:
    external: true
